### ISSUE TITLE
Bug: [v8] BpuBufferSystem.onBufferDestroy contains null gpuBuffer when destroying via react hook

### ISSUE THREAD

**Issue by levi** [pixijs/pixijs#10331]
### Current Behavior

When destroying my pixi v8 app from a React useEffect hook, I get intermittent crashes related to the GPU buffer no longer existing.

My react component has access to a global instance of my pixi app with a useEffect hook something like this:

```
  useEffect(() => {
    app.load();
    return () => {
      app.unload();
    };
  }, []);
```

And the app class looks something like this:

```
class App {
  [..]
  async load() {
    this._pixi = new Application()
    await this._pixi.init()
  }

  unload() {
    if (this._pixi && this._pixi.renderer) {
      this._pixi.destroy(false)
    }
  }
}
```

Here's the error and stacktrace

```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'destroy')

Source
GpuBufferSystem.onBufferDestroy
javascript/node_modules/pixi.js/lib/rendering/renderers/gpu/buffer/GpuBufferSystem.mjs (67:0)
eval
javascript/node_modules/pixi.js/lib/rendering/renderers/gpu/buffer/GpuBufferSystem.mjs (75:0)
Array.forEach
<anonymous>
GpuBufferSystem.destroy
javascript/node_modules/pixi.js/lib/rendering/renderers/gpu/buffer/GpuBufferSystem.mjs (75:0)
SystemRunner.emit
javascript/node_modules/pixi.js/lib/rendering/renderers/shared/system/SystemRunner.mjs (19:0)
WebGPURenderer.destroy
javascript/node_modules/pixi.js/lib/rendering/renderers/shared/system/AbstractRenderer.mjs (218:0)
_Application.destroy
javascript/node_modules/pixi.js/lib/app/Application.mjs (79:0)
src/lib/canvas/app.ts (350:17) @ destroy

  348 |
  349 | if (this._pixi && this._pixi.renderer) {
> 350 |   this._pixi.destroy(false)
      |             ^
  351 | }
  352 | this._pixi = null
  353 |
```

### Expected Behavior

No crash when using it within a useEffect hook

### Steps to Reproduce

Defined above

### Environment

- **`pixi.js` version**: 8.0.2

### Possible Solution

I assume the canvas is being destroyed before the useEffect hook is being called. I attempted to resolve this by using useLayoutEffect, but there was no difference.

**Comment by GoodBoyDigital** [comment]
this ones a little tricky to reproduce! is there a minimal example you could share pls?
in the mean time i did tweak how things are destroyed - but not 100% sure it will fix it as have been unable to repro.
thanks @levi

**Comment by levi** [comment]
@GoodBoyDigital I'll try your patch. Getting a sample repo together might take sometime on my end. Happy to screen share my project on discord if that is a helpful alternative path.

**Comment by TomSlezakowski** [comment]
Hello! I just ran into the same issue! I tried the above patch but the issue persists. 

From a little digging, it seems like the order of execution means duplicate `uid`'s are passed in to the `_destroyBuffer` function. Changing `_destroyBuffer` to `if (gpuBuffer) gpuBuffer.destroy();` was enough to get things working again for me.

Here's a log of `destroy()` with the respective buffer & uid.

```
GPUBuffer {size: 192, usage: 40, mapState: 'unmapped', label: 'attribute-batch-buffer'} - UID: 8
GPUBuffer {size: 24, usage: 24, mapState: 'unmapped', label: 'index-batch-buffer'} - UID: 9
GPUBuffer {size: 262140, usage: 76, mapState: 'unmapped', label: ''} - UID: 6
GPUBuffer {size: 262140, usage: 72, mapState: 'unmapped', label: ''} - UID: 7
null - UID: 9
null - UID: 8
```

Hope that helps, and congrats on V8! 🚀

**Comment by GoodBoyDigital** [comment]
Yes! this is super useful. hope you are well mate!

**Comment by Durss** [comment]
I also get this issue.
I have a very minimalist Vue3 app that doesn't much but instanciate a World.ts class that then does everything with PIXI.
When vue is unmounted i destroy things this way (maybe not appropriate):
```typescript
app.stage.removeAllListeners();
app.renderer.removeAllListeners();
app.destroy({removeView:true}, {children:true});
```
I also tried this much simpler way that fails the exact same way:
```typescript
app.destroy();
```

As long as I don't add more children than the ones added during first render, I can hot reload with no issue.
But as soon as a new child is added anywhere, the destroy() call breaks with the following stack:
```
chunk-6KKKYF7S.js?v=7732f24d:410 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'destroy')
    at GpuBufferSystem._destroyBuffer (chunk-6KKKYF7S.js?v=7732f24d:410:15)
    at chunk-6KKKYF7S.js?v=7732f24d:404:51
    at Array.forEach (<anonymous>)
    at GpuBufferSystem.destroy (chunk-6KKKYF7S.js?v=7732f24d:404:26)
    at SystemRunner.emit (chunk-S3Q6LN3I.js?v=7732f24d:172:21)
    at WebGPURenderer.destroy (chunk-S3Q6LN3I.js?v=7732f24d:461:26)
    at _Application2.destroy (pixi__js.js?v=086abf1e:6472:19)
```

The "_destroyBuffer" method is there on GpuBufferSystem class;
```javascript
  _destroyBuffer(buffer) {
    const gpuBuffer = this._gpuBuffers[buffer.uid];
    gpuBuffer.destroy(); //<== it fails here
    buffer.off("update", this.updateBuffer, this);
    buffer.off("change", this.onBufferChange, this);
    buffer.off("destroy", this.onBufferDestroy, this);
    this._gpuBuffers[buffer.uid] = null;
  }
```

**Comment by Durss** [comment]
Seems fixed with 8.1.0 !

Thank you :)

**Comment by konstantincheban** [comment]
I observe the same issue even with 8.1.0 version, I still see **Buffers** with duplicated **uids** which exactly cause this issue because **_managedBuffers** is an array and **_gpuBuffers** is an Object with keys as **uid**.

**Comment by zhouccccc** [comment]
Same issue with v8.1.4
<img width="213" alt="image" src="https://github.com/pixijs/pixijs/assets/25141787/bf6d0e63-332e-435d-8fd2-e204fc8ce8ec">
<img width="857" alt="image" src="https://github.com/pixijs/pixijs/assets/25141787/615ea86d-8955-4118-9efb-749c13670634">

**Comment by mrtoorich** [comment]
Same here, reproduction @bigtimebuddy :

```jsx
import { useEffect, useRef } from 'react'
import { Application } from 'pixi.js'

const Game = () => {
  const gameRef = useRef(null)
  const appRef = useRef(null)

  useEffect(() => {
    const init = async () => {
      if (gameRef.current === null) {
        return
      }
      const app = new Application()
      appRef.current = app
      await app.init({ resizeTo: window })
      gameRef.current.append(app.canvas)
    }

    init()

    return () => {
      appRef.current?.destroy(true, { children: true })
    }
  }, [])

  return (
    <div ref={gameRef}></div>
  )
}

export default Game;
```

Error message: `Cannot read properties of undefined (reading 'destroy')`.

**Comment by bigtimebuddy** [comment]
This can happen if you're using `React.StrictMode` but also if you're mount and unmounting quickly. When `StrictMode` is used then `useEffect` will run twice in development. In this case, that means that app will initialize, get destroyed before initialization is done, thereby destroy will fail. Invalid use of `destroy` here is not handled by PixiJS.

Here's an example to more insulate around the async nature of `app.init()`:
https://codesandbox.io/p/sandbox/hungry-thompson-rqspc2

Alternatively, consider using [React's `Suspense`](https://react.dev/reference/react/Suspense) which is designed exactly around handling async events typically loading.

**Comment by mrtoorich** [comment]
> This can happen if you're using `React.StrictMode` but also if you're mounting and unmounting quickly. When `StrictMode` is used then `useEffect` will run twice in development. In this case, that means that app will initialize, get destroyed before initialization is done, thereby destroy will fail. Invalid use of `destroy` here is not handled by PixiJS.
> 
> Here's an example to more insulate around the async nature of `app.init()`: https://codesandbox.io/p/sandbox/hungry-thompson-rqspc2
> 
> Alternatively, consider using [React's `Suspense`](https://react.dev/reference/react/Suspense) which is designed exactly around handling async events typically loading.

Thank you for your demo, but the `<canvas>` tag is not generated in the demo, can you have a look again? Thanks.

**Comment by bigtimebuddy** [comment]
Updated example:
https://codesandbox.io/p/sandbox/hungry-thompson-rqspc2

**Comment by Zyie** [comment]
Going to close this as this answer seems to answer the problem: https://github.com/pixijs/pixijs/issues/10331#issuecomment-2171933150
