### ISSUE TITLE
Bug: export image empty on firefox

### ISSUE THREAD

**Issue by yungzhu** [pixijs/pixijs#10361]
### Current Behavior

mac+m2+firefox 
exported image is empty but renders normally, 
it like the mask caused 

https://www.pixiplayground.com/#/edit/eWY1ZMryKd40TkiemFPL9

### Expected Behavior

https://www.pixiplayground.com/#/edit/eWY1ZMryKd40TkiemFPL9

### Steps to Reproduce

https://www.pixiplayground.com/#/edit/eWY1ZMryKd40TkiemFPL9

### Environment

- **`pixi.js` version**: *e.g. 8.0.3*
- firefox

![img_v3_0297_0af7c320-e590-498b-894f-d28e05f79a3g](https://github.com/pixijs/pixijs/assets/2418199/91e1da33-c74b-4186-898e-5e9fc91865e8)

**Comment by GoodBoyDigital** [comment]
hey @yungzhu ! i think this is fixed now? just went to test the above examples in FF and the images are downloading correctly? Perhaps a fixed upstream bug? 

Let me know if this is working for you also!

**Comment by yungzhu** [comment]
![image](https://github.com/pixijs/pixijs/assets/2418199/cf54f37a-5447-403a-b768-aadf7040edab)
Still not working, Mac m2 CPU

**Comment by yungzhu** [comment]
@GoodBoyDigital hi,has there been any progress on this bug

**Comment by hansagames** [comment]
Hi,
still reproduces on 8.9.2, any known workarounds for this ?

**Comment by sravia** [comment]
This is a somewhat expensive workaround that handles most of my cases:
```
export function convertMasksToTextures(container: Container, app: Application) {
    container.children.forEach(child => {
        convertMasksToTextures(child, app);

        if (child.mask && child.mask instanceof Graphics) {
            const maskTexture = app.renderer.textureGenerator.generateTexture(child.mask);
            const maskSprite = new Sprite(maskTexture);
            maskSprite.position.copyFrom(child.getBounds());
            child.mask = maskSprite;

            child.addChild(maskSprite);
        }
    });
}
```

**Comment by mayakwd** [comment]
@hansagames, @sravia 
Can you check with the latest version 8.13.2?

**Comment by sravia** [comment]
@mayakwd Still reproducible - https://www.pixiplayground.com/#/edit/MEUU2d99Sw0SV5zCk2Eyv
