### ISSUE TITLE
Bug: crash when WebGL2RenderingContext is not available

### ISSUE THREAD

**Issue by elsassph** [pixijs/pixijs#10391]
### Current Behavior

PixiJS 8 can't start when running in an older browser without webGl 2.0 support: 
```
Uncaught (in promise) ReferenceError: WebGL2RenderingContext is not defined
```

### Expected Behavior

I make apps for connected TVs - a lot of models still don't support webGl 2.0. Some even don't support webGl at all.

It would be great if Pixi 8 would gracefully support older browsers supporting only webGl 1.0.

### Steps to Reproduce

Run any Pixi app on an TV 3+ years old.

### Environment

- **`pixi.js` version**: 8.0
- **Browser & Version**: Chrome/53.0.2785.34 Safari/537.36
- **OS & Version**: webOS 4.10

### Possible Solution

I tried declaring a mock `WebGL2RenderingContext` class (`undefined` also fails further during init) to pass the webGl detection but then gl errors happen and nothing renders:
```
PixiJS Warning:  Provided WebGL context does not support 32 index buffer, large scenes may not render correctly
WebGL: INVALID_ENUM: activeTexture: texture unit out of range
[.Offscreen-For-WebGL-0x123eb0]GL ERROR :GL_INVALID_VALUE : glUniform1iv: texture unit out of range
```

Line of `activeTexture` error is: https://github.com/pixijs/pixijs/blob/dev/src/rendering/renderers/gl/texture/GlTextureSystem.ts#L190

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital you added support for WebGL1 in v8, right?

**Comment by elsassph** [comment]
@bigtimebuddy I see there seem to be support for webGl 1, but it crashes on systems without support for webGl 2.

**Comment by bigtimebuddy** [comment]
Yeah, I gathered that. If I had to guess, we added the internal supported for WebGL1, but probably didn't actually test running in a WebGL1-only environment.

**Comment by Zyie** [comment]
hey @elsassph what version of v8 are you using?

i believe this #10351 should fix the issue and was released in 8.0.4

**Comment by erikdubbelboer** [comment]
@Zyie the issue is still present in 8.0.4. See: https://github.com/pixijs/pixijs/issues/10401

**Comment by Zyie** [comment]
Yeah this is definitely still an issue, we will look into it!

**Comment by mwx0621** [comment]
For Safari in IOS 13.3, there is no global WebGL2RenderingContext in browser. Though this version of safari support webgl2, pixi will crash with "Can't get variable: WebGL2RenderingContext" when calling [initFromContext](https://github.com/pixijs/pixijs/blob/e60413aff2a04934197808cb07c6fba36516de21/src/rendering/renderers/gl/texture/utils/mapFormatToGlInternalFormat.ts#L22).

**Comment by Zyie** [comment]
This should be fixed in 8.1.0
