### ISSUE TITLE
What happens when WebGL context is lost?

### ISSUE THREAD

**Issue by tari3x** [pixijs/pixijs#6494]
- **`pixi.js` version**: _e.g.5.2.1
- **Browser & Version**: Firefox 74.0
- **OS & Version**:  OpenSuSE 43.1

  This is a question again: when I see "Error: WebGL context was lost.", does this mean that pixi falls back to canvas drawing? I see this when I try to load my code in Firefox and the result is very slow and laggy - the animation stutters. When opening the same script in chromium, I don't see the error message and the animation is very smooth.

  Perhaps chrome is just a lot faster? What's a good way to debug this?

**Comment by ivanpopelyshev** [comment]
> Does this mean that pixi falls back to canvas drawing

Nope, but pixi can try restore context if you call specific WebGL function. Maybe pixi can call it itself, but you have to learn what is that function anyway and search through pixijs sources to confirm that. Google "WebGL context loss".

PixiJS doesnt have diagnostic features. There's no way to know what is laggy in your case. Unless you somehow know how to debug javascript memory and CPU with devtools... Count "idle" time versus js functions, find which js functions are slow. 

Oh ! you can look in SpectorJS extension how many WebGL commands you use for animation and how much texture memory is allocated! Just capture one frame and look at it. Maybe post it here together with your memory profile, what if someone can help you by that data? 

> OpenSuSE 43.1

OMG Linux. Linux backends have a specific behaviour we dont usually know about. Your case can help the science! Please specify which drivers do you use and see if firefox has some info on graphics backend it uses

**Comment by tari3x** [comment]
I think I'll save myself deep debugging since it works fine in chrome. Here's what I observed in firefox so far. My page is like this:
```
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body> 
    <script src="external/pixi.min.js"></script>
    <script src="simple.js"></script>
  </body>
</html>
```

And simple.js is like this:

```
const app = new PIXI.Application({ antialias: true });
document.body.appendChild(app.view);
```

The output I see in console is
```
Error: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one. isWebGLSupported.ts:32:27
Error: WebGL context was lost. isWebGLSupported.ts:32:27
Error: WebGL context was lost. isWebGLSupported.ts:44:36
Error: Exceeded 16 live WebGL contexts for this principal, losing the least recently used one. ContextSystem.js:121:24
Error: WebGL context was lost. ContextSystem.js:121:24
```
And the CPU is spinning at 100% (even though I haven't drawn anything). 

If I remove both lines from simple.js then I don't see any error messages and CPU usage is low. If I remove only the second line then I do see the error messages, but the CPU usage remains low.

I did a performance recording (shift-F5) of it spinning at 100%. Firefox won't let me upload, will try with chrome in a second.

I'm not sure how to ask firefox about the graphics backend. I'm on a google pixel 2015, with an intel graphics card. Three.js demos are working without errors.

**Comment by tari3x** [comment]
Here you go, the recording:
[profile.zip](https://github.com/pixijs/pixi.js/files/4399744/profile.zip)

**Comment by ggojedap** [comment]
Hi friends, similar error here:

> Error: WebGL context was lost. triggered by **isWebGLSupported.ts:44:36**

- **pixi.js**: 5.2.1
- **Browser**: Firefox 74.0
- **OS**: MacOS 10.14.6 Mojave

The error appears when a page with a simple example is loaded. The example is working fine but it is extrange because the extension "WEBGL_lose_context" is completly supported by Firefox.

**Comment by SukantPal** [comment]
@ivanpopelyshev I think PixiJS creates a "mock" WebGL context and makes it lost during initialization. That context is not related to contexts created by application canvases.

**Comment by lululock71** [comment]
Hi, similar issues under Firefox 75 (also Firefox dev 76 beta 4). I also have this, after refreshing the page a couple of times :
`Exceeded 16 live WebGL contexts for this principal, losing the least recently used one. isWebGLSupported.js:31:32`
`WebGL context was lost. isWebGLSupported.js:31:32`

I also have serious performance issues. For example, the demo shown on PixiJS official website (https://www.pixijs.com/) is very slow and choppy and I have a lot of CPU usage as well. On Chromium, it runs smoothly and does not show any sign of lost context in console.
Other js WebGL libraries, are slow as well, it's a browser related issue.

When testing 3D WebGL examples, both browsers show slowdowns...

I've read that Firefox and Chromium works best with Wayland. Their implementation of WebGL 2 for X11 is still a work in progress, while Chromium has the best support today (but still far from being perfect, especially in 3D). Apparently, WebGL 1 is better supported for X11 but as far as I've tested, it's the same for me.
I personally use X11 (xorg), and I think that's why I have such poor performance.

The Firefox development team is currently working on it, but they started a month ago, so we will need to wait a bit before starting to see an improvement.
https://bugzilla.mozilla.org/show_bug.cgi?id=1010527
https://bugzilla.mozilla.org/show_bug.cgi?id=1580166

That's also explains why Windows users don't experience this issue, as Firefox uses DXGL to render on this platform.

MacOS users probably have performance issues as well.

- **pixi.js** : 5.1.6 (also 4.0.0 used on the official website)
- **Tested browsers** : Firefox 75, Firefox Developer Edition 76 beta 4, Chromium 81.0.4044.92
- **Distro** : Arch Linux 5.4.31-1 LTS
- **Hardware** : Ryzen 5 2400G (Vega disabled), 16GB RAM, RX 480 8GB
- **amdgpu** : 19.1.0-1
- **mesa** : 20.0.4-1
- **xorg** : 1.20.8-1

**Comment by lululock71** [comment]
UPDATE : 
The performance issues have been fixed in both the latest Firefox version and Firefox Dev version. The performance is not perfect but way more fluid than before.

But there are still lost context issues with pixi.

**Comment by eric-burel** [comment]
Ha, Stalebot, we meet again. This issue still happens for us, Firefox is losing context without much debug info nor directions on how to fix this issue. Happy to contribute to this, we have a strong interest in fixing this bug

**Comment by soanvig** [comment]
Happening for me as well. 

Pixi: 6.0.4
Firefox: 89.0.2
OS: Linux

I have exactly the same problem as @lululock71 : https://github.com/pixijs/pixijs/issues/6494#issuecomment-613312280
(with exception of source line of this warning).

I can confirm pixi demo lagging, and the same warning around.

Everything works in Chromium

**Comment by jaxankey** [comment]
Me too. Before anything else on the console, I get 

WebGL context was lost. utils.min.js:8:1488
PixiJS 6.1.3 - WebGL 2 - http://www.pixijs.com/ utils.min.js:8:1056

My system:
Pixi: 6.1.3
Firefox: 92.0
OS: Linux Mint

**Comment by exp-table** [comment]
Encountering the same issue. Even creating an empty `Application` leads to a context lost issue on Firefox. On Chrome, there is no such warning but nothing is displayed.

**Comment by Tukkan** [comment]
Happens to me when importing `Application` from `@pixi/app` instead of `'pixi.js'`.

**Comment by JoepSchyns** [comment]
With this bare-bones code snippet below I get the "Error: WebGL context was lost." in Firefox.
Some of the demo's on Github seem to run  without the error. Any directions on how to run pixijs on webgl in Firefox?

- Code snippet:
```
<!DOCTYPE html>
<html lang="">
  <head>
    <script src="https://cdn.jsdelivr.net/npm/pixi.js@7.x/dist/pixi.min.js"></script>
  </head>
  <body>
    <script>
      const app = new PIXI.Application();
      document.body.appendChild(app.view);
    </script>
  </body>
</html>
```

pixi.js version: v6 & v7
- Browser & Version: Firefox 110.0
- OS & Version: Windows 11

**Comment by SuperSodaSea** [comment]
@JoepSchyns This reason why "WebGL context was lost." message occurs in Firefox is that PixiJS creates a temporary WebGL context to detect whether WebGL is supported, then try to delete the context by using `gl.getExtension('WEBGL_lose_context').lostContext()`. This will cause Firefox to show an warning in console. It doesn't affect the normal execution of the code, just a little annoying.

![image](https://user-images.githubusercontent.com/8724868/221899609-c93dcaef-771b-4150-9e35-e6016f618003.png)

**Comment by SuperSodaSea** [comment]
> However, any way to check which renderer pixi is using? (Since "webgl context lost" is not reliable sign)

Add `hello: true` to the options for creating `Application` will show a message with renderer type in console (the message will show up automatically if you are using PixiJS v6). If you want to check this in you code, you can use `app.renderer instanceof PIXI.Renderer` for WebGL renderer and `app.renderer instanceof PIXI.CanvasRenderer` for canvas renderer.

(Your question let me found that `app.renderer.type` is broken, see #9218. After this is fixed (hopefully for 7.2.0) you can use `app.renderer.type === RENDERER_TYPE.WEBGL` and `app.renderer.type === RENDERER_TYPE.CANVAS` to check the renderer's type!)

**Comment by GoodBoyDigital** [comment]
closing due - v8 should have this stuff solved!

**Comment by Anatoly03** [comment]
~~I've met this problem as well, although it's not a warning for me. It's triggered within the `App.init()` method, for weird reasons the code for the example lib worked smoothly last weeks, but now it stopped working. I even revert to earlier commits in git where it worked but this keeps reappearing and doesn't go away. I don't recall changing browser settings either.~~

~~Safari Version 17.6 (18618.3.11.11.7, 18618)
Pixi.js Version 8.10
OS: MacOS Ventura 13.7.6 (22H625)~~

<img width="502" alt="Image" src="https://github.com/user-attachments/assets/db170551-0730-425e-ac01-524da5699342" />

```
dependencies:
    "pixi.js": "^8.10.2",
    "vue": "^3.5.17",
    "vue3-pixi": "^0.9.6"
```

EDIT: Works on newly opened Firefox window, it's a browser issue.~~

---

Fix: Completely kill browser window and restart app.
