### ISSUE TITLE
Error v6.5.1: Extension type renderer-webgl-plugin already has a handler 

### ISSUE THREAD

**Issue by Makio64** [pixijs/pixijs#8530]
After updated pixi from 6.4.x to the new 6.5.1 I got this error `Extension type renderer-webgl-plugin already has a handler `
I double checked i have only one Application started.

ps: To update: i did the yarn remove pixi.js / yarn add pixi.js

- **`pixi.js` version**: 6.5.1

**Comment by bigtimebuddy** [comment]
Can you provide a reproduction?

**Comment by bigtimebuddy** [comment]
I have a somewhat vanilla webpack/pixijs project [here](https://github.com/bigtimebuddy/pixi-sound-webpack-example) and cannot reproduce this error with 6.5.1.

**Comment by EneaEntertainment** [comment]
I was having same issue, but as @bigtimebuddy suggested me - uninstalling and also deleting lock file before new install helped

**Comment by bigtimebuddy** [comment]
Also, please read this: https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS

**Comment by Makio64** [comment]
@bigtimebuddy thanks it works when I delete the yarn.lock, but pixi is the only repo i'm using who needs this kind of extra steps to update. I guess it should be a way to avoid that.

**Comment by Zyie** [comment]
Closing as this was resolved by delete the lock file. See the [Upgrading Pixi](https://github.com/pixijs/pixijs/wiki/Upgrading-PixiJS) wiki for more info

**Comment by HiggsWRX** [comment]
This solution does not work for me.

I have followed every suggestion. Properly uninstall, remove lock file, etc.
On a clean install I still get this error when trying to load pixi
